// api
export const API = 'API_REQEST';
export const POSTS_FETCHING_STARTED = 'POSTS_FETCHING_STARTED';
export const POSTS_FETCHING_SUCCEEDED = 'POSTS_FETCHING_SUCCEEDED';
export const POSTS_FETCHING_FAILED = 'POSTS_FETCHING_FAILED';

export const USERS_FETCHING_STARTED = 'USERS_FETCHING_STARTED';
export const USERS_FETCHING_SUCCEEDED = 'USERS_FETCHING_SUCCEEDED';
export const USERS_FETCHING_FAILED = 'USERS_FETCHING_FAILED';

// posts
export const SET_POSTS = 'SET_POSTS';

// users
export const SET_USERS = 'SET_USERS';
