// api
export const API = 'FETCH_POSTS';
export const POSTS_FETCHING_STARTED = 'POSTS_FETCHING_STARTED';
export const POSTS_FETCHING_SUCCEEDED = 'POSTS_FETCHING_SUCCEEDED';
export const POSTS_FETCHING_FAILED = 'POSTS_FETCHING_FAILED';

// posts

export const SET_POSTS = 'SET_POSTS';